In [1]:
import pandas as pd
import numpy as np
import cv2
import tensorflow as tf
from tensorflow import keras

In [2]:
df = pd.read_csv('hand_gestures.csv')
df.head()

,label,x0,y0,x1,y1,x2,y2,x3,y3,x4,...,x16,y16,x17,y17,x18,y18,x19,y19,x20,y20
0,Backward,293.605289,254.533596,246.202621,240.463915,207.489796,203.971453,191.840343,158.260803,207.655506,...,270.818367,184.386907,302.729359,157.582726,283.740063,141.750698,283.747444,172.621565,291.912708,178.750362
1,Backward,277.758656,246.029348,234.871998,236.349506,197.969513,199.295540,188.843460,152.623129,202.908955,...,261.498756,181.247950,292.193775,152.562261,272.778416,135.976753,271.258221,166.127687,280.659370,172.360754
2,Backward,329.809952,239.655375,293.782234,239.442501,255.076027,199.274182,250.919876,147.912998,270.558777,...,316.298714,180.293341,344.264488,156.556191,333.580055,142.234440,331.998596,170.770926,337.514000,175.113101
3,Backward,382.145996,244.530773,345.716095,241.260824,305.123558,200.795259,299.533424,151.381545,329.183426,...,365.799561,175.578632,390.178528,156.288257,386.641655,138.644886,388.619804,164.498806,391.123581,169.105339
4,Backward,392.345047,270.843544,355.965652,262.760954,323.874435,225.447407,319.478817,181.816950,342.551956,...,382.934456,204.336033,410.889702,183.787079,401.993446,164.556341,401.199150,192.607770,404.791489,199.648004

In [3]:
df['label'].value_counts()

label
Backward    19
Up          18
Right       17
Left        15
Down        15
Forward     13
Name: count, dtype: int64

In [4]:
df['label'] = df['label'].map({'Forward': 0, 'Backward': 1, 'Up': 2, 'Down': 3, 'Left': 4, 'Right': 5})

In [5]:
input = tf.constant(df)
tensor_data = tf.random.shuffle(input)

In [6]:
x_train = tensor_data[:int(len(tensor_data)*0.9), 1:]
y_train = tensor_data[:int(len(tensor_data)*0.9), :1]

x_test = tensor_data[int(len(tensor_data)*0.9):, 1:]
y_test = tensor_data[int(len(tensor_data)*0.9):, :1]

In [7]:
x_train.shape

TensorShape([87, 42])

In [8]:
x_test.shape

TensorShape([10, 42])

In [9]:
a = pd.DataFrame(x_train)
b = pd.DataFrame(x_test)
pd.concat([a,b])

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,162.011833,260.146437,206.016388,263.622808,252.471104,237.400804,241.343555,201.553817,204.641991,193.572350,...,183.332748,197.344222,155.469913,166.826448,168.637218,159.631577,167.878914,186.809592,162.518787,190.949636
1,155.004873,280.393438,163.993378,235.363870,182.010612,197.985878,189.146824,161.455922,182.237282,134.362950,...,225.451317,264.081059,248.223248,274.057732,246.654053,280.754585,232.746544,283.495073,220.795612,282.714958
2,413.626022,389.830484,395.586586,347.303467,403.760338,294.974871,408.508873,252.758503,403.778648,220.438070,...,445.477791,358.186569,496.682205,365.234098,511.952515,364.603901,483.923454,372.439957,462.377663,372.498035
3,324.042740,311.309023,314.815788,257.563047,297.440128,210.123124,287.389431,167.853041,290.174866,132.404323,...,250.932980,293.618917,217.704811,317.798538,224.353542,313.138361,239.139385,314.228611,249.757195,316.157627
4,251.236668,369.484234,256.826744,312.405968,277.834396,268.979044,293.703976,230.036631,296.786537,203.389864,...,322.666550,332.375908,360.703621,363.388853,351.965828,349.512119,336.462250,350.872564,323.578758,356.965513
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,436.834831,410.131102,432.513084,364.119301,416.430626,327.177916,411.088943,287.153807,418.933945,257.042971,...,369.087601,376.147671,347.454147,403.887234,345.669556,387.127361,359.249763,390.097589,370.269241,395.119944
6,352.770653,325.754843,318.705177,312.654676,287.324886,281.837139,262.754765,258.901377,239.088211,248.491688,...,358.207092,145.460558,377.397995,235.363040,395.438423,213.079004,406.474457,195.840869,415.877724,178.887377
7,233.526154,364.999695,247.668209,322.854681,252.362270,274.919815,266.149902,240.766611,283.969593,217.528811,...,216.892376,313.670855,137.916698,322.677498,147.417088,297.164755,175.253506,305.204659,193.749905,314.892311
8,392.209854,284.047394,387.517319,245.151129,372.054977,208.740807,362.499809,173.473907,364.867744,144.427915,...,334.495697,271.101723,306.377983,281.963968,308.882046,285.391331,324.126778,288.581944,336.000824,288.257561
9,316.149883,358.566198,305.573940,304.696112,283.989563,261.729984,271.630993,214.357853,268.624477,177.698393,...,243.032913,336.965790,207.935314,368.727751,213.242111,357.684574,230.121574,357.943411,244.137802,359.913025

In [10]:
model = keras.Sequential([
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(256, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(8, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss = 'sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train, y_train, epochs=100, callbacks=keras.callbacks.EarlyStopping(monitor='accuracy', patience=5))

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - accuracy: 0.1181 - loss: 51.4068
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.1871 - loss: 8.6506
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3928 - loss: 3.1501
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5805 - loss: 2.0316
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6695 - loss: 1.3074
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8219 - loss: 0.6879
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7042 - loss: 0.7590
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8219 - loss: 0.5607
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.7734 - loss: 0.6567
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9400 - loss: 0.2556
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9363 - loss: 0.2376
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9363 - loss: 0.1658
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9554 - loss: 0.1362
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9632 - loss: 0.1697
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9943 - loss: 0.0584
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.0512
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.0407
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.0247
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.0262
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.0107
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.0104

In [11]:
model.evaluate(x_test, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 243ms/step - accuracy: 1.0000 - loss: 0.0116

[0.011617898941040039, 1.0]

In [12]:
model.save('landmark-model.keras')